import { storageService } from './storageService.js';

class ExportService {
  generateMarkdown(sessionId) {
    const session = storageService.getSession(sessionId);
    if (!session) return null;

    const requests = storageService.getSessionRequests(sessionId);
    const userActions = storageService.getSessionUserActions(sessionId);

    let markdown = `# API Recorder - ${session.name}\n\n`;
    markdown += `**创建时间**: ${session.createdAt.toLocaleString('zh-CN')}\n`;
    markdown += `**状态**: ${session.status === 'active' ? '录制中' : '已停止'}\n`;
    markdown += `**请求数量**: ${requests.length}\n\n`;

    markdown += `## 用户操作记录\n\n`;
    if (userActions.length > 0) {
      userActions.forEach((action, index) => {
        markdown += `${index + 1}. **${action.type.toUpperCase()}** - ${action.tagName}`;
        if (action.selector) markdown += ` (${action.selector})`;
        if (action.value) markdown += ` = "${action.value}"`;
        markdown += `\n`;
        markdown += `   - 时间: ${new Date(action.capturedAt).toLocaleString('zh-CN')}\n`;
        markdown += `   - 页面: ${action.pageUrl}\n\n`;
      });
    } else {
      markdown += `_暂无操作记录_\n\n`;
    }

    markdown += `## 接口详情\n\n`;

    requests.forEach((req, index) => {
      markdown += `### ${index + 1}. ${req.method} ${req.url}\n\n`;
      markdown += `- **状态码**: ${req.response?.status || '-'}\n`;
      markdown += `- **响应时间**: ${req.response?.time || '-'}ms\n`;
      markdown += `- **页面URL**: ${req.pageUrl}\n`;
      markdown += `- **捕获时间**: ${new Date(req.capturedAt).toLocaleString('zh-CN')}\n\n`;

      markdown += `#### 请求信息\n\n`;
      markdown += `**URL**: \`${req.url}\`\n\n`;
      markdown += `**Method**: \`${req.method}\`\n\n`;

      if (req.headers && Object.keys(req.headers).length > 0) {
        markdown += `**请求头**:\n\`\`\`json\n${JSON.stringify(req.headers, null, 2)}\n\`\`\`\n\n`;
      }

      if (req.queryParams && Object.keys(req.queryParams).length > 0) {
        markdown += `**查询参数**:\n\`\`\`json\n${JSON.stringify(req.queryParams, null, 2)}\n\`\`\`\n\n`;
      }

      if (req.body) {
        markdown += `**请求体**:\n\`\`\`json\n${typeof req.body === 'string' ? req.body : JSON.stringify(req.body, null, 2)}\n\`\`\`\n\n`;
      }

      markdown += `#### 响应信息\n\n`;
      markdown += `**状态码**: ${req.response?.status || '-'}\n\n`;

      if (req.response?.headers && Object.keys(req.response.headers).length > 0) {
        markdown += `**响应头**:\n\`\`\`json\n${JSON.stringify(req.response.headers, null, 2)}\n\`\`\`\n\n`;
      }

      if (req.response?.body) {
        markdown += `**响应体**:\n\`\`\`json\n${this.formatJson(req.response.body)}\n\`\`\`\n\n`;
      }

      markdown += `---\n\n`;
    });

    return markdown;
  }

  generateJson(sessionId) {
    const session = storageService.getSession(sessionId);
    if (!session) return null;

    const requests = storageService.getSessionRequests(sessionId);
    const userActions = storageService.getSessionUserActions(sessionId);

    return {
      session: {
        id: session.id,
        name: session.name,
        createdAt: session.createdAt,
        updatedAt: session.updatedAt,
        status: session.status,
        requestCount: requests.length
      },
      userActions: userActions.map(a => ({
        type: a.type,
        selector: a.selector,
        tagName: a.tagName,
        value: a.value,
        text: a.text,
        capturedAt: a.capturedAt,
        pageUrl: a.pageUrl
      })),
      requests: requests.map(r => ({
        method: r.method,
        url: r.url,
        headers: r.headers,
        queryParams: r.queryParams,
        body: r.body,
        response: r.response,
        capturedAt: r.capturedAt,
        pageUrl: r.pageUrl,
        type: r.type
      }))
    };
  }

  generateJmx(sessionId) {
    const session = storageService.getSession(sessionId);
    if (!session) return null;

    const requests = storageService.getSessionRequests(sessionId);

    let jmx = `<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.6.3">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="${this.escapeXml(session.name)}" enabled="true">
      <stringProp name="TestPlan.comments">Generated by API Recorder</stringProp>
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.tearDown_on_shutdown">true</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
        <collectionProp name="Arguments.arguments"/>
      </elementProp>
      <stringProp name="TestPlan.user_define_classpath"></stringProp>
    </TestPlan>
    <hashTree>
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="API Requests" enabled="true">
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControllerGui" testclass="LoopController" testname="Loop Controller" enabled="true">
          <boolProp name="LoopController.continue_forever">false</boolProp>
          <stringProp name="LoopController.loops">1</stringProp>
        </elementProp>
        <stringProp name="ThreadGroup.num_threads">1</stringProp>
        <stringProp name="ThreadGroup.ramp_time">1</stringProp>
        <boolProp name="ThreadGroup.scheduler">false</boolProp>
        <stringProp name="ThreadGroup.duration"></stringProp>
        <stringProp name="ThreadGroup.delay"></stringProp>
      </ThreadGroup>
      <hashTree>
`;

    requests.forEach((req, index) => {
      const urlObj = new URL(req.url);
      const protocol = urlObj.protocol.replace(':', '');
      const host = urlObj.hostname;
      const port = urlObj.port || (protocol === 'https' ? '443' : '80');
      const path = urlObj.pathname + urlObj.search;

      jmx += `        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="${this.escapeXml(req.method + ' ' + path)}" enabled="true">
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
            <collectionProp name="Arguments.arguments">
`;

      if (req.queryParams) {
        Object.entries(req.queryParams).forEach(([key, value]) => {
          jmx += `              <elementProp name="${this.escapeXml(key)}" elementType="HTTPArgument">
                <boolProp name="HTTPArgument.always_encode">true</boolProp>
                <stringProp name="Argument.value">${this.escapeXml(value)}</stringProp>
                <stringProp name="Argument.metadata">=</stringProp>
                <boolProp name="HTTPArgument.use_equals">true</boolProp>
                <stringProp name="Argument.name">${this.escapeXml(key)}</stringProp>
              </elementProp>
`;
        });
      }

      jmx += `            </collectionProp>
          </elementProp>
          <stringProp name="HTTPSampler.domain">${this.escapeXml(host)}</stringProp>
          <stringProp name="HTTPSampler.port">${port}</stringProp>
          <stringProp name="HTTPSampler.protocol">${protocol}</stringProp>
          <stringProp name="HTTPSampler.contentEncoding"></stringProp>
          <stringProp name="HTTPSampler.path">${this.escapeXml(path)}</stringProp>
          <stringProp name="HTTPSampler.method">${req.method}</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
          <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
          <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
          <stringProp name="HTTPSampler.connect_timeout"></stringProp>
          <stringProp name="HTTPSampler.response_timeout"></stringProp>
`;

      if (req.headers) {
        Object.entries(req.headers).forEach(([key, value]) => {
          jmx += `          <elementProp name="${this.escapeXml(key)}" elementType="Header">
            <stringProp name="Header.name">${this.escapeXml(key)}</stringProp>
            <stringProp name="Header.value">${this.escapeXml(value)}</stringProp>
          </elementProp>
`;
        });
      }

      if (req.body) {
        const bodyContent = typeof req.body === 'string' ? req.body : JSON.stringify(req.body);
        jmx += `          <boolProp name="HTTPSampler.postBodyRaw">true</boolProp>
          <stringProp name="HTTPSampler.requestBody">${this.escapeXml(bodyContent)}</stringProp>
`;
      }

      jmx += `        </HTTPSamplerProxy>
        <hashTree/>
`;
    });

    jmx += `      </hashTree>
    </hashTree>
  </hashTree>
</jmeterTestPlan>
`;

    return jmx;
  }

  escapeXml(str) {
    if (!str) return '';
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }

  formatJson(str) {
    try {
      const obj = typeof str === 'string' ? JSON.parse(str) : str;
      return JSON.stringify(obj, null, 2);
    } catch {
      return str;
    }
  }
}

export const exportService = new ExportService();
